spring:
  application:
    name: spring-cloud-service-consumer
server:
  port: 8000
  servlet:
    context-path: /consumer
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
